{% set name = "dspawpy" %}
{% set version = "1.8.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f1381266c63e77caf1523daf49cd4346b77a2e797de2fb5937f00935bd2cb4ca

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true
  entry_points:
    - dspawpy=dspawpy.cli.entrypoint:main

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - pymatgen
    - statsmodels
    - h5py
    - prompt_toolkit
    - loguru
    - polars >=0.18
    - h5glance
    - pytables
    - numpy <2
    - ase

test:
  imports:
    - dspawpy
    - dspawpy.analysis
    - dspawpy.cli
    - dspawpy.diffusion
    - dspawpy.io
  commands:
    - pip check
    - dspawpy --help
  requires:
    - pip

about:
  home: http://www.hzwtech.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tools for dspaw
  doc_url: http://hzwtech.com/Device%20Studio/DS-PAW/build/html/tools.html
  dev_url: http://hzwtech.com/Device%20Studio/DS-PAW/build/html/dspawpy/latest/dspawpy.html

extra:
  recipe-maintainers:
    - bernt-matthias
    - DeeliN221
    - HZWzzl
