{% set name = "dspawpy" %}
{% set version = "1.8.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6da7b47e0797600362f08f8ba8fa875a12a304b931c767d178e962c37e7564ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - dspawpy=dspawpy.cli.entrypoint:main

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - uv-build >=0.9.8,<0.10
  run:
    - python >=3.9,<3.13
    - pymatgen
    - statsmodels
    - h5py
    - prompt_toolkit
    - loguru
    - polars >=0.18
    - h5glance
    - pytables
    - numpy <2
    - ase

test:
  imports:
    - dspawpy
    - dspawpy.analysis
    - dspawpy.cli
    - dspawpy.diffusion
    - dspawpy.io
  commands:
    - pip check
    - dspawpy --help
  requires:
    - pip

about:
  home: http://www.hzwtech.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tools for dspaw
  doc_url: http://hzwtech.com/Device%20Studio/DS-PAW/build/html/tools.html
  dev_url: http://hzwtech.com/Device%20Studio/DS-PAW/build/html/dspawpy/latest/dspawpy.html

extra:
  recipe-maintainers:
    - bernt-matthias
    - DeeliN221
    - HZWzzl
